### ISSUE TITLE
dependencies not recorded correctly

### ISSUE THREAD

**Issue by mbjones** [NCEAS/recordr#42]
viewRun() only shows a few package dependencies, whereas it really should be showing everything in the session that has been loaded.

**Comment by sbpcs59** [comment]
Now "base", "other" and "loadedOnly" packages are recorded in the execution metadata, for example:
Dependencies: stats, graphics, grDevices, utils, datasets, methods, base, hash_2.2.6, Rcpp_0.12.3, magrittr_1.5, roxygen2_5.0.1, munsell_0.4.2, uuid_0.1-2, colorspace_1.2-6, R6_2.1.2, stringr_1.0.0, httr_1.1.0, plyr_1.8.3, tools_3.2.3, grid_3.2.3, redland_1.0.17-4, gtable_0.1.2, parsedate_1.1.1, datapackage_1.0.0, DBI_0.3.1, yaml_2.1.13, digest_0.6.9, ggplot2_2.0.0, base64enc_0.1-3, bitops_1.0-6, RCurl_1.95-4.7, RSQLite_1.0.0, stringi_1.0-1, scales_0.3.0, XML_3.98-1.3, jsonlite_0.9.19, recordr_0.9.0.9006, dataone_2.0.0, EML_0.0-6

Fixed in commit dfca11ce08d05f3417dafc41df37487fad7eb5fb
